Add buildagent profile
ls1intum/artemis-ansible-collection pull request #67
Opened 2024-02-04 12:19 UTC by laurenzfb

This PR adds a new profile `buildagent` to the local CI setup. Please deploy after [#7979] has been merged (https://github.com/ls1intum/Artemis/pull/7979).

2024-02-12 12:32 UTC, Mtze submitted a review, later dismissed

2024-02-16 15:14 UTC, Hialus requested changes

2024-02-16 15:32 UTC, bensofficial commented on roles/artemis/templates/application-prod.yml.j2
> +{% endif %}
Done

2024-02-16 15:33 UTC, bensofficial approved these changes

2024-02-19 17:45 UTC, Hialus approved these changes
Looks good and works on Staging

2024-02-21 08:36 UTC, Mtze approved these changes

2024-02-21 08:40 UTC, merged